### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by www-jh** [dani-capellan/LightTBNet#1]
Thanks for the code. By the way, where can i get this paper? Thanks for your reply！

**Comment by dani-capellan** [comment]
Hi!

The corresponding paper has been accepted for publication at ISBI 2023 (proceedings). It should be out very soon... If you have any further concerns, you can reach me via email - daniel.capellan@upm.es, or post another issue as well.

Regards,

Daniel

**Comment by dani-capellan** [comment]
Hi @www-jh, please find here the paper: https://doi.org/10.1109/ISBI53787.2023.10230500

Regards,

Daniel
